acts_camdram_infobase_article:
    type:     rest
    resource: ActsCamdramInfobaseBundle:Article

acts_camdram_infobase_tag:
    type:     rest
    resource: ActsCamdramInfobaseBundle:Tag

acts_camdram_infobase_index:
    path: /
    defaults: { _controller: ActsCamdramInfobaseBundle:Default:index }
